### ISSUE TITLE
Option to select Google regionalized/localized domain?

### ISSUE THREAD

**Issue by aramic** [brendandc/multilingual-google-image-scraper#1]
I notice that Google often gives different results depending on the domain; for example, the results for looking up the word "pas" on google.com vs. on google.ba are quite different. I've hardcoded in manually what I need, but it might be a "nice to have" feature to be able to specify which regional Google domain to use in the options as well.

Thank you for this very, very useful script !

**Comment by brendandc** [comment]
Thanks for the feedback and good catch on the results being different! (even with hl/lr language tuning flags active)

I added a new flag at the command line `-D` which when provided will override the `google.com` with `google.<any domain suffix>`. https://github.com/brendandc/multilingual-google-image-scraper/commit/3ea46c1b1cdb1bc407d81e28b50898cb3e5f7859

**Comment by aramic** [comment]
That's so awesome ! Thank you @brendandc  : )
